#!/usr/bin/env bash
# Generates install/04_rbac.yaml by combining operator and operand RBAC.
#
# Sources:
#   pkg/assets/operator/rbac.yaml    — operator's own RBAC (hand-maintained)
#   pkg/assets/karpenter/*.yaml      — core operand RBAC
#   pkg/assets/aws/*.yaml            — AWS operand RBAC
#
# The operator SA needs a superset of every operand permission (to satisfy
# Kubernetes RBAC escalation checks when managing operand Roles/ClusterRoles).
#
# Usage:
#   hack/manifest-diff.sh          # diff only (exit 1 if install/ is stale)
#   hack/manifest-diff.sh --sync   # regenerate install/04_rbac.yaml
#
# Requires: yq (auto-installed via `make sync-manifests`)

set -euo pipefail

NAMESPACE="openshift-karpenter"
OPERAND_NAME="karpenter-operator-operand"
SA_NAME="karpenter-operator"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ASSETS_DIR="${REPO_ROOT}/pkg/assets/karpenter"
AWS_ASSETS_DIR="${REPO_ROOT}/pkg/assets/aws"
OPERATOR_RBAC="${REPO_ROOT}/pkg/assets/operator/rbac.yaml"
INSTALL_RBAC="${REPO_ROOT}/install/04_rbac.yaml"
MODE="${1:-}"

YQ="${YQ:-yq}"
command -v "$YQ" &>/dev/null || { echo "ERROR: yq required" >&2; exit 1; }

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

# --- Collect operand rules ----------------------------------------------------
collect_rules() {
  local result=""
  for f in "$@"; do
    [[ -f "$f" ]] || continue
    local rules
    rules=$($YQ eval '.rules' "$f" 2>/dev/null)
    if [[ -n "$result" ]]; then
      result+=$'\n'"${rules}"
    else
      result="$rules"
    fi
  done
  echo "$result"
}

operand_cr_rules=$(collect_rules "${ASSETS_DIR}"/clusterrole-*.yaml "${AWS_ASSETS_DIR}"/clusterrole.yaml)
operand_role_rules=$(collect_rules "${ASSETS_DIR}"/role.yaml)

# --- Build output -------------------------------------------------------------
emit_annotations() {
  cat <<'ANN'
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/feature-set: DevPreviewNoUpgrade
ANN
}

{
  cat <<'HEADER'
# DO NOT EDIT. Generated by hack/manifest-diff.sh --sync from:
#   pkg/assets/operator/rbac.yaml    (operator's own RBAC + cross-ns operand RBAC)
#   pkg/assets/karpenter/*.yaml       (operand RBAC, mirrored to operator SA)
HEADER

  cat "$OPERATOR_RBAC"

  if [[ -n "$operand_cr_rules" ]]; then
    echo "---"
    echo "apiVersion: rbac.authorization.k8s.io/v1"
    echo "kind: ClusterRole"
    echo "metadata:"
    echo "  name: ${OPERAND_NAME}"
    echo "  annotations:"
    emit_annotations
    echo "rules:"
    # yq outputs bare arrays at column 0; re-indent to match upstream
    echo "  ${operand_cr_rules//$'\n'/$'\n'  }"
    echo "---"
    echo "apiVersion: rbac.authorization.k8s.io/v1"
    echo "kind: ClusterRoleBinding"
    echo "metadata:"
    echo "  name: ${OPERAND_NAME}"
    echo "  annotations:"
    emit_annotations
    echo "subjects:"
    echo "  - kind: ServiceAccount"
    echo "    name: ${SA_NAME}"
    echo "    namespace: ${NAMESPACE}"
    echo "roleRef:"
    echo "  kind: ClusterRole"
    echo "  name: ${OPERAND_NAME}"
    echo "  apiGroup: rbac.authorization.k8s.io"
  fi

  if [[ -n "$operand_role_rules" ]]; then
    echo "---"
    echo "apiVersion: rbac.authorization.k8s.io/v1"
    echo "kind: Role"
    echo "metadata:"
    echo "  name: ${OPERAND_NAME}"
    echo "  namespace: ${NAMESPACE}"
    echo "  annotations:"
    emit_annotations
    echo "rules:"
    # yq outputs bare arrays at column 0; re-indent to match upstream
    echo "  ${operand_role_rules//$'\n'/$'\n'  }"
    echo "---"
    echo "apiVersion: rbac.authorization.k8s.io/v1"
    echo "kind: RoleBinding"
    echo "metadata:"
    echo "  name: ${OPERAND_NAME}"
    echo "  namespace: ${NAMESPACE}"
    echo "  annotations:"
    emit_annotations
    echo "subjects:"
    echo "  - kind: ServiceAccount"
    echo "    name: ${SA_NAME}"
    echo "    namespace: ${NAMESPACE}"
    echo "roleRef:"
    echo "  kind: Role"
    echo "  name: ${OPERAND_NAME}"
    echo "  apiGroup: rbac.authorization.k8s.io"
  fi
} > "${tmpdir}/04_rbac.yaml"

# --- Diff or sync -------------------------------------------------------------
if [[ "$MODE" == "--sync" ]]; then
  cp "${tmpdir}/04_rbac.yaml" "$INSTALL_RBAC"
  echo "==> Synced. Review:"
  echo "      git diff install/04_rbac.yaml"
  exit 0
fi

if diff -q "${tmpdir}/04_rbac.yaml" "$INSTALL_RBAC" &>/dev/null; then
  echo "==> In sync."
else
  echo "==> install/04_rbac.yaml is stale:"
  diff -u "$INSTALL_RBAC" "${tmpdir}/04_rbac.yaml" \
    --label "current" --label "expected" || true
  echo ""
  echo "==> OUT OF SYNC. Run: hack/manifest-diff.sh --sync"
  exit 1
fi
