#!/usr/bin/env bash
# Syncs or diffs operand RBAC/SA from the OpenShift karpenter-provider-aws fork
# Helm chart into pkg/assets/karpenter/ and pkg/assets/aws/.
#
# Downloads the chart at a pinned branch, renders it with `helm template`, then
# extracts RBAC resources with yq, stripping Helm labels.
#
# When upstream adds new RBAC resources, this script will fail and list them.
# To handle a new resource, add an `extract KIND NAME FILE` call in the
# appropriate section (core or AWS) below, then re-run.
#
# Usage:
#   hack/manifest-diff-upstream.sh          # diff only (exit 1 if out of sync)
#   hack/manifest-diff-upstream.sh --sync   # overwrite assets from fork chart
#
# Requires: curl; helm, yq (auto-installed via `make manifest-diff-sync`)

set -euo pipefail

REPO_NAME="openshift/aws-karpenter-provider-aws"
OPERAND_BRANCH="release-5.0"
NAMESPACE="openshift-karpenter"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CORE_DIR="${REPO_ROOT}/pkg/assets/karpenter"
AWS_DIR="${REPO_ROOT}/pkg/assets/aws"
MODE="${1:-}"

YQ="${YQ:-yq}"
HELM="${HELM:-helm}"
for tool in curl "$YQ" "$HELM"; do
  command -v "$tool" &>/dev/null || { echo "ERROR: $tool not found" >&2; exit 1; }
done

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

# --- Download & render -------------------------------------------------------
echo "==> Fetching ${REPO_NAME} @ ${OPERAND_BRANCH}..."
curl -sSL --retry 3 --retry-delay 2 "https://github.com/${REPO_NAME}/archive/refs/heads/${OPERAND_BRANCH}.tar.gz" | tar -xz -C "$tmpdir"
chart_dir=$(find "$tmpdir" -type d -name karpenter -path "*/charts/karpenter" 2>/dev/null | head -1)
[[ -n "$chart_dir" ]] || { echo "ERROR: failed to fetch chart" >&2; exit 1; }
rm -rf "${chart_dir}/crds"

echo "==> Rendering Helm chart..."
$HELM template karpenter "$chart_dir" \
  --namespace "$NAMESPACE" --skip-crds \
  --set "settings.clusterName=placeholder" \
  > "${tmpdir}/rendered.yaml"

# --- Extract resources --------------------------------------------------------
core_staging="${tmpdir}/core"
aws_staging="${tmpdir}/aws"
mkdir -p "$core_staging" "$aws_staging"

# Strip Helm-injected labels; keep functional ones like aggregate-to-admin.
strip='
  del(.metadata.labels["helm.sh/chart"]) |
  del(.metadata.labels["app.kubernetes.io/managed-by"]) |
  del(.metadata.labels["app.kubernetes.io/instance"]) |
  del(.metadata.labels["app.kubernetes.io/version"]) |
  del(.metadata.labels["app.kubernetes.io/name"]) |
  del(.metadata.annotations) |
  del(.metadata.labels | select(length == 0))
'

header="# DO NOT EDIT. Generated by hack/manifest-diff-upstream.sh from ${REPO_NAME} ${OPERAND_BRANCH}"

# extract KIND NAME FILE — pull one doc, strip helm metadata, write with header
extracted_names=""
extract() {
  local kind="$1" name="$2" file="$3"
  extracted_names+="${kind}/${name}"$'\n'
  local selected
  selected=$($YQ eval-all "select(.kind == \"$kind\" and .metadata.name == \"$name\")" "${tmpdir}/rendered.yaml")
  if [[ -z "$selected" ]]; then
    echo "ERROR: no document found for ${kind}/${name}" >&2
    exit 1
  fi
  printf '%s\n' "$header" > "$file"
  echo "$selected" | $YQ eval "$strip" - >> "$file"
}

echo "==> Extracting resources..."

# --- Core (cloud-agnostic, pkg/assets/karpenter/) ---
extract ClusterRole        karpenter-core  "${core_staging}/clusterrole-core.yaml"
extract ClusterRoleBinding karpenter-core  "${core_staging}/clusterrolebinding-core.yaml"
extract Role               karpenter       "${core_staging}/role.yaml"
extract RoleBinding        karpenter       "${core_staging}/role-binding.yaml"
extract Role               karpenter-dns   "${core_staging}/role-dns.yaml"
extract RoleBinding        karpenter-dns   "${core_staging}/role-binding-dns.yaml"
extract ClusterRole        karpenter-admin "${core_staging}/aggregate-clusterrole.yaml"

# --- AWS (provider-specific, pkg/assets/aws/) ---
extract ClusterRole        karpenter "${aws_staging}/clusterrole.yaml"
extract ClusterRoleBinding karpenter "${aws_staging}/clusterrolebinding.yaml"

# --- Validate: no unhandled RBAC resources ------------------------------------
rendered_names=$($YQ eval '.kind + "/" + .metadata.name' "${tmpdir}/rendered.yaml" \
  | grep -E "^(Role|RoleBinding|ClusterRole|ClusterRoleBinding)/" | sort -u)

unhandled=$(comm -23 <(echo "$rendered_names") <(echo "$extracted_names" | sort -u))
if [[ -n "$unhandled" ]]; then
  echo "ERROR: upstream has RBAC resources not handled by this script:"
  echo "    ${unhandled//$'\n'/$'\n'    }"
  echo "  Add extract calls for them, then re-run."
  exit 1
fi

# --- Diff or sync -------------------------------------------------------------
diff_dir() {
  local staging="$1" target="$2" label="$3"
  local rc=0
  for f in "${staging}"/*.yaml; do
    [[ -f "$f" ]] || continue
    local base target_file
    base=$(basename "$f")
    target_file="${target}/${base}"
    if [[ ! -f "$target_file" ]]; then
      echo "MISSING: ${label}/${base}"; rc=1; continue
    fi
    local norm_up="${tmpdir}/u-${base}" norm_lo="${tmpdir}/l-${base}"
    grep -v '^\s*#' "$f"           | $YQ eval '.' - > "$norm_up" 2>/dev/null || true
    grep -v '^\s*#' "$target_file" | $YQ eval '.' - > "$norm_lo" 2>/dev/null || true
    if ! diff -q "$norm_up" "$norm_lo" &>/dev/null; then
      echo "DIFF: ${label}/${base}"
      diff -u "$norm_up" "$norm_lo" --label "upstream/${base}" --label "local/${base}" || true
      rc=1
    fi
  done
  for f in "${target}"/*.yaml; do
    [[ -f "$f" ]] || continue
    [[ -f "${staging}/$(basename "$f")" ]] || { echo "EXTRA: ${label}/$(basename "$f")"; rc=1; }
  done
  return $rc
}

if [[ "$MODE" == "--sync" ]]; then
  rm -f "${CORE_DIR}"/*.yaml
  cp "${core_staging}"/*.yaml "${CORE_DIR}/"
  rm -f "${AWS_DIR}"/*.yaml
  cp "${aws_staging}"/*.yaml "${AWS_DIR}/"
  echo "==> Synced. Review:"
  echo "      git diff pkg/assets/karpenter/"
  echo "      git diff pkg/assets/aws/"
  exit 0
fi

echo "==> Comparing..."
exitcode=0
diff_dir "$core_staging" "$CORE_DIR" "pkg/assets/karpenter" || exitcode=1
diff_dir "$aws_staging" "$AWS_DIR" "pkg/assets/aws" || exitcode=1

if [[ $exitcode -eq 0 ]]; then
  echo "==> In sync with ${REPO_NAME} ${OPERAND_BRANCH}."
else
  echo "==> OUT OF SYNC. Run: hack/manifest-diff-upstream.sh --sync"
fi
exit $exitcode
